export const AUDIO_PROCESSING_QUEUE_PORT = Symbol('AUDIO_PROCESSING_QUEUE_PORT');
export const TRANSCRIPTION_PORT = Symbol('TRANSCRIPTION_PORT');
export const AUDIO_SUMMARY_PORT = Symbol('AUDIO_SUMMARY_PORT');
export const PROCESSED_AUDIO_QUEUE_PORT = Symbol('PROCESSED_AUDIO_QUEUE_PORT');
export const AUDIO_ERROR_QUEUE_PORT = Symbol('AUDIO_ERROR_QUEUE_PORT');
export const PROCESSED_AUDIO_DELIVERY_PORT = Symbol('PROCESSED_AUDIO_DELIVERY_PORT');
export const AUDIO_ERROR_DELIVERY_PORT = Symbol('AUDIO_ERROR_DELIVERY_PORT');
export const QR_CODE_DISPLAY_PORT = Symbol('QR_CODE_DISPLAY_PORT');
